# Generated by Django 3.1 on 2024-02-19 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_avalailable',
            new_name='is_available',
        ),
    ]
