# Generated by Django 3.1 on 2024-02-20 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20240219_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descripption',
            new_name='description',
        ),
    ]
