# Generated by Django 5.0.2 on 2024-03-07 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_productgallery_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'product gallery', 'verbose_name_plural': 'product gallery'},
        ),
    ]
